# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies without running lifecycle scripts
RUN npm install --ignore-scripts

# Copy all source files
COPY . .

# Run build command
RUN npm run build

# Expose port if needed (not required for stdio transport, but added for future use)
EXPOSE 3000

# Start the MCP server
CMD [ "node", "src/index.js" ]
